#!/usr/bin/env bash

# Install Nginx web server
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y

# Allow Nginx through firewall
sudo ufw allow 'Nginx HTTP'

# Create a HTML file for the redirection message
echo "
	<html>
		<head>
			<title>301 Moved Permanently</title>
		</head>
		<body>
			<h1>301 Moved Permanently</h1>
			<p>The document has moved <a href=\"https://www.youtube.com/watch?v=QH2-TGUlwu4\">here</a>.</p>
		</body>
	</html>" | sudo tee /var/www/html/redirect_me.html > /dev/null

# Configure Nginx to redirect /redirect_me
sudo sh -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default'

# Restart Nginx
sudo service nginx restart

