#!/usr/bin/env bash

# Update system and install Nginx
sudo apt update -y
sudo apt install nginx -y

# Create directory for additional configuration (optional)
sudo mkdir -p /etc/nginx/conf.d

# Replace line with multiple lines using sed
sudo sed -i '/server {/a \
location /redirect_me { \
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
} \
' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
