#!/usr/bin/env bash
# Installs nginx web server

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://twitter.com/Emmanue17280546;
    }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
