#!/usr/bin/env bash
#Bash script that:
#  Creates the file /var/run/myscript.pid containing its PID
#  Displays To infinity and beyond indefinitely
#  Displays I hate the kill command when receiving a SIGTERM signal
#  Displays Y U no love me?! when receiving a SIGINT signal
#  Deletes the file /var/run/myscript.pid and terminates
#itself when receiving a SIGQUIT or SIGTERM signal

count=1

PIDFILE="/var/run/myscript.pid"
touch $PIDFILE
echo $$ > $PIDFILE

trap 'echo I hate the kill command; rm $PIDFILE; kill -SIGKILL $$' SIGTERM
trap 'echo Y U no love me?!; kill -SIGINTll $$' SIGINT

while [ $count ]
do
	echo "To infinity and beyond"
	sleep 2 
done
