#!/usr/bin/env bash
#Bash script that loops from 1 to 10

c=1
while [[ $c -le 10 ]]
do
	if [[ $c -eq 4 ]]
	then
		echo "bad luck"
	elif [[ $c -eq 8 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	c=$((c+1))
done
