#!/usr/bin/env bash
#Bash script that gives you information about the school file

file="school"
if [[ -e "$file" ]]
then
	echo "school file exists"
	if [[ -s "$file" ]]
	then
		echo "school file does not empty"
	else
		echo "school file is empty"
	fi
	if [[ -f "$file" ]]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
